import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import { getRepoStructure, readRepoFile } from "@/services/readRepository";
import MainNav from "@/components/MainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // const response = await getRepoStructure();
  const rootDir = await readRepoFile();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navigation route={response} /> */}
        <MainNav rootNav={rootDir} />
        {children}
      </body>
    </html>
  );
}
