import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import SearchBar from './SearchBar';
import Banner from '@/components/Banner';
import { classNames } from '@/components/Marulloc-UI-v2/utils/classNames';
import Navigation from '@/components/Navigation';
import ConsoleCompo from '@/components/Marulloc-UI-v2/components/ConsoleCompo';
import SideCart from '@/components/SideCart';
import RecoilProvider from '@/recoils/_RecoilProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, ' ')} suppressHydrationWarning={true}>
        <RecoilProvider>
          <Banner />
          <div className="">
            <SideCart />
            <Navigation />
          </div>
          {children}
        </RecoilProvider>
      </body>
    </html>
  );
}
